name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore TodoApp.API
    
    - name: Build
      run: dotnet build TodoApp.API --no-restore
    
    - name: Test
      run: dotnet test TodoApp.API --no-build --verbosity normal
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    
    - name: Install frontend dependencies
      run: npm ci
      working-directory: todo-app-frontend
    
    - name: Build frontend
      run: npm run build
      working-directory: todo-app-frontend